### ISSUE TITLE
Feature: Replace node-web-audio api in example

### ISSUE THREAD

**Issue by ramirezd42** [ramirezd42/vst-js#7]
The node-web-audio-api library is causing some problems in the example script (see: https://github.com/ramirezd42/vst-js/issues/3)

I should look for a more reliable replacement and replace it with that.

**Comment by connorhartley** [comment]
I'd have a look at some of the audiojs ecosystem modules. Specifically: https://github.com/audiojs/web-audio-api

**Comment by ramirezd42** [comment]
Thanks! I'll definitely give it a whirl

**Comment by ramirezd42** [comment]
I swapped in audiojs' web-audio-api implementation in the example and the problems in #3 were not improved much if at all. I'm guessing that wasn't actually the problem in the first place, so I'm closing this and re-opening that issue so it's still visible.
