### ISSUE TITLE
Npm package not found?

### ISSUE THREAD

**Issue by BasicPro** [ramirezd42/vst-js#9]
Hi!
I wanted to try out your project but I get a 404 error when installing, did you take it down from npm? 
Regards

**Comment by BasicPro** [comment]
I'm still trying to install this, it is really promising for my project.

**Comment by ramirezd42** [comment]
Hey sorry about that. I had to step away from this project for a bit, and never actually had it published on npm. Its up now https://www.npmjs.com/package/vstjs a

There are a few other dependencies you need to get before npm install will build successfully, but those are detailed in the readme.

Happy hacking!
